## name: Selene Abyss
## license: MIT
## author: envoidia
## upstream: https://github.com/envoidia/selene-abyss

background #161b29
foreground #cccac2
selection_background #30485c
selection_foreground #cccac2
url_color #66c8cc
cursor #66c8cc
cursor_text_color #172038

# Tabs
active_tab_background #bb94de
active_tab_foreground #161b29
inactive_tab_background #66c8cc
inactive_tab_foreground #172038

# Windows
active_border_color #e9aee4
inactive_border_color #253a5e

# normal
color0 #161b29
color1 #f7768e
color2 #32bb99
color3 #e9aee4
color4 #6798ff
color5 #a673d3
color6 #66c8cc
color7 #b5c0ff

# bright
color8  #253a5e
color9  #ff899d
color10 #4fc1a5
color11 #efbceb
color12 #8db0ff
color13 #bb94de
color14 #a4daff
color15 #c0caf5
